name: Feature request
about: Suggest an idea to improve the plugin
title: "[FEAT]: "
labels: ['enhancement']
assignees:
  - BrakingChanges

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the feature is.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I'd like it if...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Are there any alternatives to this solution? Are there any alternatives that can be used right now?
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

